<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_609561ce24689',
	'title' => 'Block: Key points',
	'fields' => array(
		array(
			'key' => 'field_609716dbcb99c',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '(optional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60956377c1956',
			'label' => 'Key points',
			'name' => 'key_points',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 1,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add key point',
			'sub_fields' => array(
				array(
					'key' => 'field_60956210280f9',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_flexible_advanced' => 0,
					'layouts' => array(
						'layout_609562234ee21' => array(
							'key' => 'layout_609562234ee21',
							'name' => 'standard',
							'label' => 'Standard',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_60956244280fa',
									'label' => '',
									'name' => 'standard',
									'type' => 'text',
									'instructions' => 'This should be limited to 3-5 words',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
							'min' => '',
							'max' => '1',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_settings' => false,
							'acfe_flexible_settings_size' => 'medium',
							'acfe_flexible_modal_edit_size' => false,
							'acfe_flexible_category' => false,
						),
						'layout_60956268280fc' => array(
							'key' => 'layout_60956268280fc',
							'name' => 'large',
							'label' => 'Large',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_60956271280fd',
									'label' => '',
									'name' => 'large',
									'type' => 'text',
									'instructions' => 'This should be limited to a number or single word',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
							'min' => '',
							'max' => '1',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_settings' => false,
							'acfe_flexible_settings_size' => 'medium',
							'acfe_flexible_modal_edit_size' => false,
							'acfe_flexible_category' => false,
						),
					),
					'button_label' => 'Add text',
					'min' => '',
					'max' => '',
					'acfe_flexible_stylised_button' => false,
					'acfe_flexible_hide_empty_message' => false,
					'acfe_flexible_empty_message' => '',
					'acfe_flexible_layouts_templates' => false,
					'acfe_flexible_layouts_previews' => false,
					'acfe_flexible_layouts_placeholder' => false,
					'acfe_flexible_layouts_thumbnails' => false,
					'acfe_flexible_layouts_settings' => false,
					'acfe_flexible_disable_ajax_title' => false,
					'acfe_flexible_layouts_ajax' => false,
					'acfe_flexible_add_actions' => array(
					),
					'acfe_flexible_remove_button' => array(
					),
					'acfe_flexible_layouts_state' => false,
					'acfe_flexible_modal_edit' => array(
						'acfe_flexible_modal_edit_enabled' => false,
						'acfe_flexible_modal_edit_size' => 'large',
					),
					'acfe_flexible_modal' => array(
						'acfe_flexible_modal_enabled' => false,
						'acfe_flexible_modal_title' => false,
						'acfe_flexible_modal_size' => 'full',
						'acfe_flexible_modal_col' => '4',
						'acfe_flexible_modal_categories' => false,
					),
					'acfe_flexible_async' => array(
					),
				),
			),
		),
		array(
			'key' => 'field_60983a2484989',
			'label' => 'Background colour',
			'name' => 'style',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_6097d72758a9c',
			),
			'display' => 'seamless',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 0,
			'choices' => array(
				'Yellow' => 'Yellow',
				'Green 1' => 'Green 1',
				'Green 2' => 'Green 2',
				'Green 3' => 'Green 3',
				'Grey' => 'Grey',
				'Dark' => 'Dark',
			),
		),
		array(
			'key' => 'field_61e421ef7fc5e',
			'label' => 'Text colour',
			'name' => 'text_colour',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_61df3e284b5e1',
			),
			'display' => 'seamless',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 0,
			'choices' => array(
				'White' => 'White',
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1642340877,
));

endif;